services:
  - name: lms-backend
    type: web
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/your-app-name.jar
    env: java
    envVars:
      SERVER_PORT: 8081
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://localhost:8761/eureka/
      EUREKA_CLIENT_REGISTER-WITH-EUREKA: "true"
      EUREKA_CLIENT_FETCH-REGISTRY: "true"
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/lmsbackend
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: co37x74bob
      SPRING_JPA_SHOW-SQL: "true"
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG
      SPRING_SECURITY_USER_NAME: Benjamin
      SPRING_SECURITY_USER_PASSWORD: co37x74bob
      SPRING_MAIN_ALLOW-CIRCULAR-REFERENCES: "true"
      SPRING_APPLICATION_NAME: lmsbackend
      APP_JWTSECRET: BLde8wvZW+xspgStlAY9itRpvkzLycMKPcqaJJRdFgctE+LvYWIwfjF51uNT2du3Qi4B09tKgxF5YOUHMkDvwg==
      APP_JWTEXPIRATIONMS: 3155760000000
