services:
  - type: web
    name: lmseureka
    env: docker
    buildCommand: ./gradlew build -x test
    envVars:
      - key: SERVER_PORT
        value: "8081"
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: "http://localhost:8761/eureka/"
      - key: EUREKA_CLIENT_REGISTER-WITH-EUREKA
        value: "true"
      - key: EUREKA_CLIENT_FETCH-REGISTRY
        value: "true"
      - key: SPRING_DATASOURCE_URL
        value: "jdbc:postgresql://localhost:5432/lmsbackend"
      - key: SPRING_DATASOURCE_USERNAME
        value: "postgres"
      - key: SPRING_DATASOURCE_PASSWORD
        value: "co37x74bob"
      - key: SPRING_JPA_SHOW-SQL
        value: "true"
      - key: SPRING_JPA_HIBERNATE_DDL-AUTO
        value: "update"
      - key: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB
        value: "DEBUG"
      - key: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
        value: "DEBUG"
      - key: SPRING_SECURITY_USER_NAME
        value: "Benjamin"
      - key: SPRING_SECURITY_USER_PASSWORD
        value: "co37x74bob"
      - key: SPRING_MAIN_ALLOW-CIRCULAR-REFERENCES
        value: "true"
      - key: SPRING_APPLICATION_NAME
        value: "lmseureka"
      - key: APP_JWTSECRET
        value: "BLde8wvZW+xspgStlAY9itRpvkzLycMKPcqaJJRdFgctE+LvYWIwfjF51uNT2du3Qi4B09tKgxF5YOUHMkDvwg=="
      - key: APP_JWTEXPIRATIONMS
        value: "3155760000000"
